### ISSUE TITLE
Request  for  help

### ISSUE THREAD

**Issue by xiongxuechun** [huiqu18/FullNet-varCE#12] opened 2020-10-25 02:06 UTC
When I was running test.py, there was such a result, what is the problem?
<img width="551" alt="bug" src="https://user-images.githubusercontent.com/73398310/97097273-c7110e80-16a9-11eb-94d5-524e0d4412e1.PNG">
<img width="313" alt="bug2" src="https://user-images.githubusercontent.com/73398310/97097274-ca0bff00-16a9-11eb-8031-2150cfa0f9da.PNG">

**Comment by huiqu18** [comment] 2020-10-27 19:26
@xiongxuechun The first problem occurred because pred and target had different shapes, please check the input.
The second problem was caused by count=0, i.e., no true positives in the results. This can be fixed by ``` dice /= (count + 1e-8) ```

**Closed as completed** 2020-11-08 11:28 UTC
